import(plugin) multipleLanguages
import(theme) customTheme1

print("Bubble Script Concept")

system do
  var file = create.file(lua)
  file.parent = self.parent
  file.content is
    print("This LUA file was written in BubbleScript!")
    wait(1)
    script:Destroy()
  end
end

> Comment <

>

Comments can also work like this.

<

> My idea for Bubble Script is that it is simple to use and make it have a lot of posibilities. <
